FROM python:3.6-onbuild

ENV PYTHONUNBUFFERED 1
ENV POSTGRES_USER vagrant
ENV POSTGRES_PW vagrant
ENV POSTGRES_URL localhost:5432
ENV POSTGRES_DB vagrant
ENV HOST 0.0.0.0
ENV PORT 8732

EXPOSE 8732

ENTRYPOINT ["python"]
CMD ["app.py"]